### ISSUE TITLE
Invalid invite - discord 

### ISSUE THREAD

**Issue by aniketrochwani** [casbin/SummerOfCode2023#1]
Team, I am trying to join https://discord.com/invite/PD9g8wE6X9 provided in the ReadME. But I am getting "Invite invalid".

**Comment by hsluoyz** [comment]
@aniketrochwani it's not invalid. You can try it again.

![image](https://user-images.githubusercontent.com/3787410/218692536-7d34fe73-399d-4ca9-af5c-a7b2d733b632.png)

**Comment by aniketrochwani** [comment]
Thank you @hsluoyz. It's working.
